---
jira:
  projectKey: "HV"
  ignore:
    # See the `build-dependencies` group in the Dependabot's configuration file
    - user: dependabot[bot]
      # Examples:
      # Bump some-dep-GAV from some-version to some-version in the build-dependencies group
      # Bump the build-dependencies group with 2 updates
      titlePattern: "Bump.*the build-dependencies group( with \\d+ updates?)?"
  ignoreFiles:
    # Git
    - ".git*"
    - ".mailmap"
    # Maven
    - "mvnw*"
    - ".mvn/"
    # CI
    - ".github/"
    - "jenkins/"
    - "Jenkinsfile"
    - "*/Jenkinsfile"
    - "*.Jenkinsfile"
    - "*.sh"
    # In-repo documentation
    - "copyright.txt"
    - "README.md"
    - "MAINTAINERS.md"
    - "CONTRIBUTING.md"
