---
jira:
  projectKey: "HV"
  ignore:
    # See the `build-dependencies` group in the Dependabot's configuration file
    - user: dependabot[bot]
      # Examples:
      # Bump some-dep-GAV from some-version to some-version in the build-dependencies group
      # Bump the build-dependencies group with 2 updates
      titlePattern: "Bump.*the (build-dependencies|workflow-actions) group.*+"
  ignoreFiles:
    # Git
    - ".git*"
    - ".mailmap"
    # Maven
    - "mvnw*"
    - ".mvn/"
    # CI
    - ".github/"
    - "jenkins/"
    - "Jenkinsfile"
    - "*/Jenkinsfile"
    - "*.Jenkinsfile"
    - "*.sh"
    # In-repo documentation
    - "copyright.txt"
    - "README.md"
    - "MAINTAINERS.md"
    - "CONTRIBUTING.md"
develocity:
  buildScan:
    addCheck: true
    tags:
      - column: "OS"
        pattern: "Linux"
      - column: "OS"
        pattern: "Windows.*"
        replacement: "Windows"
      - column: "Java"
        pattern: "jdk-(.*)"
        replacement: "$1"
      - column: "TCK mode"
        pattern: "(.+)-TCK"
        replacement: "$1"
      - column: "TCK Version"
        pattern: "Validation-TCK-(.+)"
        replacement: "$1"
      - pattern: "org.hibernate.validator|Hibernate Validator|main|HEAD|\\d+.\\d+|PR-\\d+"
        replacement: "" # Just remove these tags
licenseAgreement:
  enabled: true
  ignore:
    # We ignore all dependabot PRs for a license check:
    - user: dependabot[bot]
      titlePattern: "Bump.*"
