sonar.host.url=https://sonarcloud.io
sonar.organization=hibernate
sonar.projectKey=hibernate_hibernate-validator
sonar.projectName=Hibernate Validator
sonar.projectDescription=Hibernate Validator, declare and validate application constraints.

sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.modules=hibernate-validator-annotation-processor,hibernate-validator-cdi,hibernate-validator,hibernate-validator-test-utils

hibernate-validator-annotation-processor.sonar.projectName=Hibernate Validator - Annotation Processor
hibernate-validator-annotation-processor.sonar.projectBaseDir=annotation-processor
hibernate-validator-annotation-processor.sonar.sources=src/main/java
hibernate-validator-annotation-processor.sonar.tests=src/test/java
hibernate-validator-annotation-processor.sonar.java.binaries=target/classes

hibernate-validator-cdi.sonar.projectName=Hibernate Validator - Portable Extension
hibernate-validator-cdi.sonar.projectBaseDir=cdi
hibernate-validator-cdi.sonar.sources=src/main/java
hibernate-validator-cdi.sonar.tests=src/test/java
hibernate-validator-cdi.sonar.java.binaries=target/classes

hibernate-validator.sonar.projectName=Hibernate Validator - Engine
hibernate-validator.sonar.projectBaseDir=engine
hibernate-validator.sonar.sources=src/main/java
hibernate-validator.sonar.tests=src/test/java
hibernate-validator.sonar.java.binaries=target/classes

hibernate-validator-test-utils.sonar.projectName=Hibernate Validator - Test Utils
hibernate-validator-test-utils.sonar.projectBaseDir=test-utils
hibernate-validator-test-utils.sonar.sources=src/main/java
hibernate-validator-test-utils.sonar.java.binaries=target/classes
