// SPDX-License-Identifier: Apache-2.0
// Copyright Red Hat Inc. and Hibernate Authors
[[validator-further-reading]]
== Further reading

Last but not least, a few pointers to further information.

A great source for examples is the Jakarta Validation TCK which is available for anonymous access on
https://github.com/jakartaee/validation-tck/[GitHub]. In particular the TCK's
https://github.com/jakartaee/validation-tck/tree/main/tests[tests] might be
of interest. {bvSpecUrl}[The Jakarta Validation] specification itself
is also a great way to deepen your understanding of Jakarta Validation and Hibernate Validator.

If you have any further questions about Hibernate Validator or want to share some of your use cases,
have a look at the http://community.jboss.org/en/hibernate/validator[Hibernate Validator
Wiki], the https://discourse.hibernate.org/c/hibernate-validator[Hibernate Validator Forum] and the
https://stackoverflow.com/questions/tagged/hibernate-validator[Hibernate Validator tag on Stack Overflow].

In case you would like to report a bug use
https://hibernate.atlassian.net/projects/HV/[Hibernate's Jira] instance.
Feedback is always welcome!
