/*
 * Hibernate Validator, declare and validate application constraints
 *
 * License: Apache License, Version 2.0
 * See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.
 */

@Library('hibernate-jenkins-pipeline-helpers') _

import org.hibernate.jenkins.pipeline.helpers.version.Version

env.PROJECT = "validator"
// Set to `true` *only* on branches where you want a scheduled release.
// Also uncomment the `FULLY_AUTOMATIC` property and related steps.
def RELEASE_ON_SCHEDULE = true

// Avoid running the pipeline on branch indexing
if (currentBuild.getBuildCauses().toString().contains('BranchIndexingCause')) {
	print "INFO: Build skipped due to trigger being Branch Indexing"
	currentBuild.result = 'NOT_BUILT'
	return
}

def manualRelease = currentBuild.getBuildCauses().toString().contains( 'UserIdCause' )
def cronRelease = currentBuild.getBuildCauses().toString().contains( 'TimerTriggerCause' )

// Only do automatic release on branches where we opted in
if ( !manualRelease && !cronRelease ) {
	print "INFO: Build skipped because automated releases on push are disabled on this branch."
	currentBuild.result = 'NOT_BUILT'
	return
}

if ( !manualRelease && cronRelease && !RELEASE_ON_SCHEDULE ) {
	print "INFO: Build skipped because automated releases are disabled on this branch. See constant RELEASE_ON_SCHEDULE in ci/release/Jenkinsfile"
	currentBuild.result = 'NOT_BUILT'
	return
}

def checkoutReleaseScripts() {
	dir('.release/scripts') {
		checkout scmGit(branches: [[name: '*/main']], extensions: [],
				userRemoteConfigs: [[credentialsId: 'ed25519.Hibernate-CI.github.com',
									 url: 'https://github.com/hibernate/hibernate-release-scripts.git']])
	}
}

pipeline {
	agent {
		label 'Release'
	}
    triggers {
        cron('0 15 * * 0')
    }
	tools {
		maven 'Apache Maven 3.8'
		jdk 'OpenJDK 17 Latest'
	}
	options {
		buildDiscarder logRotator(daysToKeepStr: '30', numToKeepStr: '10')
		disableConcurrentBuilds(abortPrevious: false)
	}
	parameters {
		booleanParam(
				name: 'FULLY_AUTOMATIC',
				defaultValue: true,
				description: 'If true, simulate the "timer triggered release", without asking for any release/development versions and trigger the Jira release.'
		)
		string(
				name: 'RELEASE_VERSION',
				defaultValue: '',
				description: 'The version to be released, e.g. 7.1.0.Final.',
				trim: true
		)
		string(
				name: 'DEVELOPMENT_VERSION',
				defaultValue: '',
				description: 'The next version to be used after the release, e.g. 7.2.0-SNAPSHOT.',
				trim: true
		)
		booleanParam(
				name: 'RELEASE_DRY_RUN',
				defaultValue: false,
				description: 'If true, just simulate the release, without pushing any commits or tags, and without uploading any artifacts or documentation.'
		)
	}
	stages {
	    stage('Validate release type') {
            steps {
                script {
                    if (params.FULLY_AUTOMATIC) {
                        print "INFO: Manually requested a fully automatic release."
                        def warning = ''
                        if (params.RELEASE_VERSION) {
                            warning += "Release version MUST be empty, but got '${params.RELEASE_VERSION}'."
                        }
                        if (params.DEVELOPMENT_VERSION) {
                            warning += "Development version MUST be empty, but got '${params.DEVELOPMENT_VERSION}'."
                        }
                        if (warning) {
                            throw new Exception("Cannot proceed with a release: ${warning}")
                        }
                        manualRelease = false
                        cronRelease = true
                    }
                }
            }
        }
		stage('Release') {
			when {
				beforeAgent true
				// Releases must be triggered explicitly
				// This is just for safety; normally the Jenkins job for this pipeline
				// should be configured to "Suppress automatic SCM triggering"
				// See https://stackoverflow.com/questions/58259326/prevent-jenkins-multibranch-pipeline-from-triggering-builds-for-new-branches
				triggeredBy cause: "UserIdCause"
			}
			steps {
				script {
					print "INFO: params.RELEASE_VERSION = ${params.RELEASE_VERSION}"
                    print "INFO: params.DEVELOPMENT_VERSION = ${params.DEVELOPMENT_VERSION}"
                    print "INFO: params.RELEASE_DRY_RUN? = ${params.RELEASE_DRY_RUN}"

                    print "INFO: manualRelease = ${manualRelease}"
                    print "INFO: cronRelease = ${cronRelease}"

                    checkoutReleaseScripts()
                    def derivedDryRun = params.RELEASE_DRY_RUN
                    def currentVersion = Version.parseDevelopmentVersion( sh(
                            script: ".release/scripts/determine-current-version.sh ${env.PROJECT}",
                            returnStdout: true
                    ).trim() )
                    echo "Workspace version: ${currentVersion}"

                    def releaseVersion
                    def developmentVersion

                    if ( manualRelease ) {
                        echo "Release was requested manually"

                        if ( !params.RELEASE_VERSION ) {
                            throw new IllegalArgumentException(
                                    'Missing value for parameter RELEASE_VERSION. This parameter must be set explicitly to prevent mistakes.'
                            )
                        }
                        releaseVersion = Version.parseReleaseVersion( params.RELEASE_VERSION )

                        if ( !releaseVersion.toString().startsWith( currentVersion.family + '.' ) ) {
                            throw new IllegalArgumentException( "RELEASE_VERSION = $releaseVersion, which is different from the family of CURRENT_VERSION = $currentVersion. Did you make a mistake?" )
                        }
                    }
                    else {
                        echo "Release was triggered automatically"

                        // Avoid doing an automatic release if there are no "releasable" commits since the last release (see release scripts for determination)
                        def releasableCommitCount = sh(
                                script: ".release/scripts/count-releasable-commits.sh ${env.PROJECT}",
                                returnStdout: true
                        ).trim().toInteger()
                        if ( releasableCommitCount <= 0 ) {
                            print "INFO: Automatic release skipped because no releasable commits were pushed since the previous release"
                            currentBuild.getRawBuild().getExecutor().interrupt(Result.NOT_BUILT)
                            sleep(1)   // Interrupt is not blocking and does not take effect immediately.
                            return
                        }

                        releaseVersion = Version.parseReleaseVersion( sh(
                                script: ".release/scripts/determine-release-version.sh ${currentVersion}",
                                returnStdout: true
                        ).trim() )

                        derivedDryRun = false
                    }
                    env.JRELEASER_DRY_RUN = derivedDryRun
                    env.ADDITIONAL_SCRIPT_ARGS = "${derivedDryRun ? ' -d ' : ''}"
                    echo "Derived dry run: ${derivedDryRun}"
                    echo "Additional script arguments: ${env.ADDITIONAL_SCRIPT_ARGS}"
                    echo "Release version: ${releaseVersion}"

                    if ( !params.DEVELOPMENT_VERSION ) {
                        developmentVersion = Version.parseDevelopmentVersion( sh(
                                script: ".release/scripts/determine-development-version.sh ${releaseVersion}",
                                returnStdout: true
                        ).trim() )
                    }
                    else {
                        developmentVersion = Version.parseDevelopmentVersion( params.DEVELOPMENT_VERSION )
                    }
                    echo "Development version: ${developmentVersion}"

                    env.RELEASE_VERSION = releaseVersion.toString()
                    env.DEVELOPMENT_VERSION = developmentVersion.toString()

                    echo "Performing full release for version ${releaseVersion.toString()}"

					withMaven(mavenSettingsConfig: params.RELEASE_DRY_RUN ? null : 'ci-hibernate.deploy.settings.maven',
							mavenLocalRepo: env.WORKSPACE_TMP + '/.m2repository') {
						configFileProvider([configFile(fileId: 'release.config.ssh', targetLocation: env.HOME + '/.ssh/config'),
											configFile(fileId: 'release.config.ssh.knownhosts', targetLocation: env.HOME + '/.ssh/known_hosts')]) {
							// using MAVEN_GPG_PASSPHRASE (the default env variable name for passphrase in maven gpg plugin)
							withCredentials([file(credentialsId: 'release.gpg.private-key', variable: 'RELEASE_GPG_PRIVATE_KEY_PATH'),
											 string(credentialsId: 'release.gpg.passphrase', variable: 'JRELEASER_GPG_PASSPHRASE'),
											 usernamePassword(credentialsId: 'central.sonatype.com', passwordVariable: 'JRELEASER_MAVENCENTRAL_TOKEN', usernameVariable: 'JRELEASER_MAVENCENTRAL_USERNAME'),
											 string(credentialsId: 'Hibernate-CI.github.com', variable: 'JRELEASER_GITHUB_TOKEN')]) {
								sshagent(['ed25519.Hibernate-CI.github.com', 'jenkins.in.relation.to']) {
									sh 'cat $HOME/.ssh/config'

									sh """
										bash -xe .release/scripts/release.sh -j ${env.ADDITIONAL_SCRIPT_ARGS} \
												validator ${releaseVersion.toString()} ${developmentVersion.toString()}
									"""
								}
							}
						}
					}
				}
			}
		}
		stage('Release on Jira') {
            when { expression { return cronRelease } }
            steps {
                script {
                    checkoutReleaseScripts()

                    withCredentials([string(credentialsId: 'release-webhook.hibernate.atlassian.net', variable: 'JIRA_WEBHOOK_SECRET')]) {
                        sh ".release/scripts/jira-release.sh ${env.ADDITIONAL_SCRIPT_ARGS} ${env.PROJECT} ${env.RELEASE_VERSION} ${env.DEVELOPMENT_VERSION}"
                    }
                }
            }
        }
        stage('Update website') {
            when { expression { return cronRelease } }
            steps {
                script {
                    checkoutReleaseScripts()

                    configFileProvider([
                            configFile(fileId: 'release.config.ssh', targetLocation: "${env.HOME}/.ssh/config"),
                            configFile(fileId: 'release.config.ssh.knownhosts', targetLocation: "${env.HOME}/.ssh/known_hosts")
                    ]) {
                        sshagent( ['ed25519.Hibernate-CI.github.com'] ) {
                            dir( '.release/hibernate.org' ) {
                                checkout scmGit(
                                        branches: [[name: '*/production']],
                                        extensions: [],
                                        userRemoteConfigs: [[credentialsId: 'ed25519.Hibernate-CI.github.com', url: 'git@github.com:hibernate/hibernate.org.git']]
                                )
                                sh "../scripts/website-release.sh ${env.SCRIPT_OPTIONS} ${env.PROJECT} ${env.RELEASE_VERSION}"
                            }
                        }
                    }
                }
            }
        }
	}
	post {
		always {
			notifyBuildResult notifySuccessAfterSuccess: true, maintainers: 'marko@hibernate.org'
		}
	}
}
