# SPDX-License-Identifier: Apache-2.0
# Copyright Red Hat Inc. and Hibernate Authors

name: CI reporting

on:
  workflow_run:
    workflows: [ "GH Actions CI" ]
    types: [ completed ]

permissions: { }

jobs:
  report:
    uses: hibernate/.github/.github/workflows/ci-reporting.yml@f95c7959b0b60c30a8c006cf506f25141d759575 # main
    secrets: inherit
