# SPDX-License-Identifier: Apache-2.0
# Copyright Red Hat Inc. and Hibernate Authors

name: PR cleanup

on:
  pull_request_target:
    types: [ closed ]

permissions: { }

jobs:
  cleanup:
    uses: hibernate/.github/.github/workflows/pr-cleanup.yml@f95c7959b0b60c30a8c006cf506f25141d759575 # main
    secrets: inherit
